/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ElectionResults {
  export type ResultStruct = {
    question: string;
    options: string[];
    date: string;
    tally: BigNumberish[][];
    turnout: BigNumberish;
    totalVotingPower: BigNumberish;
    participants: string[];
    action: BytesLike;
    censusRoot: BytesLike;
    censusURI: string;
  };

  export type ResultStructOutput = [
    question: string,
    options: string[],
    date: string,
    tally: bigint[][],
    turnout: bigint,
    totalVotingPower: bigint,
    participants: string[],
    action: string,
    censusRoot: string,
    censusURI: string
  ] & {
    question: string;
    options: string[];
    date: string;
    tally: bigint[][];
    turnout: bigint;
    totalVotingPower: bigint;
    participants: string[];
    action: string;
    censusRoot: string;
    censusURI: string;
  };
}

export interface ElectionResultsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getResult"
      | "owner"
      | "renounceOwnership"
      | "results"
      | "setResult"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "getResult",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "results",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setResult",
    values: [BytesLike, BytesLike, ElectionResults.ResultStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ElectionResults extends BaseContract {
  connect(runner?: ContractRunner | null): ElectionResults;
  waitForDeployment(): Promise<this>;

  interface: ElectionResultsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getResult: TypedContractMethod<
    [communityId: BytesLike, electionId: BytesLike],
    [ElectionResults.ResultStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  results: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [string, string, bigint, bigint, string, string, string] & {
        question: string;
        date: string;
        turnout: bigint;
        totalVotingPower: bigint;
        action: string;
        censusRoot: string;
        censusURI: string;
      }
    ],
    "view"
  >;

  setResult: TypedContractMethod<
    [
      communityId: BytesLike,
      electionId: BytesLike,
      result: ElectionResults.ResultStruct
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [communityId: BytesLike, electionId: BytesLike],
    [ElectionResults.ResultStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [string, string, bigint, bigint, string, string, string] & {
        question: string;
        date: string;
        turnout: bigint;
        totalVotingPower: bigint;
        action: string;
        censusRoot: string;
        censusURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setResult"
  ): TypedContractMethod<
    [
      communityId: BytesLike,
      electionId: BytesLike,
      result: ElectionResults.ResultStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
